---
- hosts: localhost

  tasks:
    - name: Update Ansible Tower inventory
      uri:
       url: https://13.233.93.98/api/v2/inventories
       user: admin
       method: POST
       body: '{ "name" : "13.233.93.98", "organisation": "1"}'
       force_basic_auth: yes
       status_code: 201
       body_format: json
       validate_certs: no
